import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { createDailyCommand } from './daily.js';

vi.mock('@ai-pm/core/workflows', () => ({
  generateDailyBriefing: vi.fn().mockReturnValue({
    date: '2026-06-19',
    projectId: 'local-project',
    topPriorities: ['Review project status', 'Deploy v2.1.0'],
    urgentBlockers: ['CI pipeline broken'],
    risksToReview: ['Database migration risk'],
    pendingApprovals: ['Approve release PR'],
    suggestedFollowups: ['Reply to vendor'],
    sourceCoverage: ['local-memory'],
    assumptions: ['Live data from configured MCP connectors.'],
    confidence: 85,
  }),
}));

vi.mock('@ai-pm/core/runtime', () => ({
  LocalProjectStore: vi.fn().mockImplementation(() => ({
    loadDailyBriefingItems: vi.fn().mockResolvedValue([]),
  })),
  MemoryStore: vi.fn().mockImplementation(() => ({})),
  ApprovalQueue: vi.fn().mockImplementation(() => ({})),
}));

vi.mock('@ai-pm/mcp/connectionManager', () => ({
  loadMcpConfig: vi.fn().mockReturnValue({
    version: '1.0',
    servers: [{ id: 'test', enabled: true, name: 'test', type: 'custom' }],
  }),
}));

describe('daily CLI — output formats', () => {
  let spy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => { spy = vi.spyOn(console, 'log').mockImplementation(() => {}); });
  afterEach(() => { spy.mockRestore(); });

  it('text format (default)', async () => {
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('Daily Briefing');
    expect(out).toContain('Review project status');
    expect(out).toContain('Confidence: 85%');
  });

  it('--format json outputs valid JSON', async () => {
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily', '--format', 'json']);
    const parsed = JSON.parse(spy.mock.calls.map(c => String(c[0])).join(''));
    expect(parsed.date).toBe('2026-06-19');
    expect(parsed.confidence).toBe(85);
  });

  it('--json flag outputs valid JSON', async () => {
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily', '--json']);
    const parsed = JSON.parse(spy.mock.calls.map(c => String(c[0])).join(''));
    expect(parsed.date).toBe('2026-06-19');
    expect(parsed.topPriorities).toContain('Review project status');
  });

  it('--format markdown', async () => {
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily', '--format', 'markdown']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('# Daily Briefing');
    expect(out).toContain('**Top Priorities:**');
    expect(out).toContain('- Review project status');
    expect(out).toContain('*Generated by AI-PM Toolkit*');
  });

  it('--format html', async () => {
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily', '--format', 'html']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('<!DOCTYPE html>');
    expect(out).toContain('<h1>Daily Briefing</h1>');
    expect(out).toContain('Generated by AI-PM Toolkit');
  });
});

describe('daily CLI — degraded source', () => {
  let spy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => { spy = vi.spyOn(console, 'log').mockImplementation(() => {}); });
  afterEach(() => { spy.mockRestore(); });

  it('no servers → yellow warning', async () => {
    vi.mocked(await import('@ai-pm/mcp/connectionManager')).loadMcpConfig.mockReturnValue({
      version: '1.0', servers: [{ id: 'x', enabled: false, name: 'x', type: 'custom' }],
    });
    const cmd = createDailyCommand();
    await cmd.parseAsync(['daily']);
    expect(spy.mock.calls.map(c => String(c[0])).join('')).toContain('No MCP servers configured');
    vi.mocked(await import('@ai-pm/mcp/connectionManager')).loadMcpConfig.mockReturnValue({
      version: '1.0', servers: [{ id: 'test', enabled: true, name: 'test', type: 'custom' }],
    });
  });
});

describe('daily CLI — structure', () => {
  it('has correct name and options', () => {
    const cmd = createDailyCommand();
    expect(cmd.name()).toBe('daily');
    const flags = cmd.options.map(o => o.long);
    expect(flags).toContain('--format');
    expect(flags).toContain('--json');
    expect(flags).toContain('--output');
  });
});
