import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { createDailyCommand } from './daily.js';

vi.mock('@ai-pm/core/workflows', () => ({
  generateContextualBriefing: vi.fn().mockResolvedValue({
    date: '2026-06-19',
    projectId: 'local-project',
    topPriorities: ['Review project status', 'Deploy v2.1.0'],
    meetingsToPrepare: [],
    urgentBlockers: ['CI pipeline broken'],
    risksToReview: ['Database migration risk'],
    pendingApprovals: ['Approve release PR'],
    suggestedFollowups: ['Reply to vendor'],
    memoryTasks: { total: 0, active: 0, completed: 0 },
    memoryArtifacts: { total: 0, active: 0 },
    connectorStatus: {},
    sourceCoverage: ['local-memory'],
    degradedSources: [],
    assumptions: ['Live data from configured MCP connectors.'],
    confidence: 85,
  }),
}));

vi.mock('ora', () => ({
  default: () => ({
    start: function () { return this; },
    succeed: function () { return this; },
    fail: function () { return this; },
    stop: function () { return this; },
    text: '',
  }),
}));

vi.mock('chalk', () => ({
  default: new Proxy({}, { get: () => (...args: unknown[]) => args.join('') }),
  green: (...args: unknown[]) => args.join(''),
  yellow: (...args: unknown[]) => args.join(''),
  red: (...args: unknown[]) => args.join(''),
  gray: (...args: unknown[]) => args.join(''),
  bold: (...args: unknown[]) => args.join(''),
  blue: (...args: unknown[]) => args.join(''),
}));

async function runWithArgv(argv: string[], spy: ReturnType<typeof vi.spyOn>): Promise<void> {
  const originalArgv = process.argv;
  const originalExit = process.exit;
  process.argv = ['node', 'daily', ...argv];
  process.exit = (() => { /* no-op */ }) as never;
  try {
    const cmd = createDailyCommand();
    await cmd.parseAsync(process.argv, { from: 'user' });
    await new Promise(r => setTimeout(r, 100));
  } finally {
    process.argv = originalArgv;
    process.exit = originalExit;
  }
}

describe('daily CLI — output formats', () => {
  let spy: ReturnType<typeof vi.spyOn>;
  let errSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    spy = vi.spyOn(console, 'log').mockImplementation(() => {});
    errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
  });
  afterEach(() => { spy.mockRestore(); errSpy.mockRestore(); });

  it('text format (default)', async () => {
    await runWithArgv([], spy);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('Daily Briefing');
    expect(out).toContain('Review project status');
    expect(out).toContain('Confidence: 85%');
  });

  it('--format json outputs valid JSON', async () => {
    await runWithArgv(['--format', 'json'], spy);
    const out = spy.mock.calls.map(c => String(c[0])).join('');
    const parsed = JSON.parse(out);
    expect(parsed.date).toBe('2026-06-19');
    expect(parsed.confidence).toBe(85);
  });

  it('--json flag outputs valid JSON', async () => {
    await runWithArgv(['--json'], spy);
    const out = spy.mock.calls.map(c => String(c[0])).join('');
    const parsed = JSON.parse(out);
    expect(parsed.date).toBe('2026-06-19');
    expect(parsed.topPriorities).toContain('Review project status');
  });

  it('--format markdown', async () => {
    await runWithArgv(['--format', 'markdown'], spy);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('# Daily Briefing');
    expect(out).toContain('**Top Priorities:**');
    expect(out).toContain('- Review project status');
    expect(out).toContain('*Generated by AI-PM Toolkit*');
  });

  it('--format html', async () => {
    await runWithArgv(['--format', 'html'], spy);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('<!DOCTYPE html>');
    expect(out).toContain('<h1>Daily Briefing</h1>');
    expect(out).toContain('Generated by AI-PM Toolkit');
  });
});

describe('daily CLI — structure', () => {
  it('has correct name and options', () => {
    const cmd = createDailyCommand();
    expect(cmd.name()).toBe('daily');
    const flags = cmd.options.map(o => o.long);
    expect(flags).toContain('--format');
    expect(flags).toContain('--json');
    expect(flags).toContain('--output');
  });

  it('createDailyCommand returns fresh instance each call', () => {
    const a = createDailyCommand();
    const b = createDailyCommand();
    expect(a).not.toBe(b);
    expect(a.name()).toBe(b.name());
  });
});
