import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { createWeeklyCommand } from './weekly.js';

vi.mock('@ai-pm/core/runtime', () => ({
  LocalProjectStore: vi.fn().mockImplementation(() => ({
    loadWeeklyReportItems: vi.fn().mockResolvedValue([]),
  })),
  ApprovalQueue: vi.fn().mockImplementation(() => ({})),
}));

vi.mock('@ai-pm/core/workflows', () => ({
  generateWeeklyReportForProject: vi.fn().mockResolvedValue({
    report: {
      accomplishments: ['Deployed v2.1.0', 'Fixed critical bug'],
      nextWeekFocus: ['Start Phase 2', 'Security audit'],
      riskSummary: ['Database migration risk'],
      decisions: ['Approved scope change'],
      milestones: [{ name: 'Sprint 13', dueDate: '2026-06-21', daysRemaining: 2 }],
      assumptions: ['Live data from local weekly items.'],
      confidence: 85,
    },
    approvalItemId: 'APR-001',
  }),
}));

vi.mock('@ai-pm/mcp/connectionManager', () => ({
  loadMcpConfig: vi.fn().mockReturnValue({
    version: '1.0',
    servers: [{ id: 'test', enabled: true, name: 'test', type: 'custom' }],
  }),
}));

describe('weekly CLI — output formats', () => {
  let spy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => { spy = vi.spyOn(console, 'log').mockImplementation(() => {}); });
  afterEach(() => { spy.mockRestore(); });

  it('text format (default)', async () => {
    const cmd = createWeeklyCommand();
    await cmd.parseAsync(['weekly', '--start', '2026-06-16', '--end', '2026-06-21']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('Weekly Status Report');
    expect(out).toContain('2026-06-16 to 2026-06-21');
    expect(out).toContain('Deployed v2.1.0');
    expect(out).toContain('Confidence: 85%');
  });

  it('--format json outputs valid JSON', async () => {
    const cmd = createWeeklyCommand();
    await cmd.parseAsync(['weekly', '--format', 'json', '--start', '2026-06-16', '--end', '2026-06-21']);
    const parsed = JSON.parse(spy.mock.calls.map(c => String(c[0])).join(''));
    expect(parsed.period.start).toBe('2026-06-16');
    expect(parsed.period.end).toBe('2026-06-21');
    expect(parsed.report.confidence).toBe(85);
    expect(parsed.approvalItemId).toBe('APR-001');
  });

  it('--json flag outputs valid JSON', async () => {
    const cmd = createWeeklyCommand();
    await cmd.parseAsync(['weekly', '--json', '--start', '2026-06-16', '--end', '2026-06-21']);
    const parsed = JSON.parse(spy.mock.calls.map(c => String(c[0])).join(''));
    expect(parsed.report.confidence).toBe(85);
  });

  it('--format markdown', async () => {
    const cmd = createWeeklyCommand();
    await cmd.parseAsync(['weekly', '--format', 'markdown', '--start', '2026-06-16', '--end', '2026-06-21']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('# Weekly Status Report');
    expect(out).toContain('**Accomplishments**');
    expect(out).toContain('- Deployed v2.1.0');
    expect(out).toContain('*Generated by AI-PM Toolkit*');
  });

  it('--format html', async () => {
    const cmd = createWeeklyCommand();
    await cmd.parseAsync(['weekly', '--format', 'html', '--start', '2026-06-16', '--end', '2026-06-21']);
    const out = spy.mock.calls.map(c => String(c[0])).join('\n');
    expect(out).toContain('<!DOCTYPE html>');
    expect(out).toContain('<h1>Weekly Status Report</h1>');
    expect(out).toContain('Generated by AI-PM Toolkit');
  });
});

describe('weekly CLI — structure', () => {
  it('has correct name and options', () => {
    const cmd = createWeeklyCommand();
    expect(cmd.name()).toBe('weekly');
    const flags = cmd.options.map(o => o.long);
    expect(flags).toContain('--format');
    expect(flags).toContain('--json');
    expect(flags).toContain('--output');
    expect(flags).toContain('--start');
    expect(flags).toContain('--end');
  });
});
