import type { TemplateEntry } from './templateRegistry.js';

// ── Render output types ──────────────────────────────────────────────────────

export type RenderFormat = 'markdown' | 'html' | 'json';

export interface RenderedArtifact {
  templateId: string;
  format: RenderFormat;
  content: string;
  metadata: ArtifactMetadata;
}

export interface ArtifactMetadata {
  templateId: string;
  templateName: string;
  category: string;
  workflow: string;
  ownerRole: string;
  approvalRequired: boolean;
  renderedAt: string;
  version: string;
  inputKeys: string[];
}

// ── Markdown renderer ────────────────────────────────────────────────────────

function renderMarkdown(template: TemplateEntry, data: Record<string, unknown>): string {
  const lines: string[] = [];

  lines.push(`# ${template.name}`);
  lines.push('');
  lines.push(`> ${template.description}`);
  lines.push('');

  // Section for each input field
  for (const key of template.required_inputs) {
    const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const value = data[key];

    lines.push(`## ${label}`);
    lines.push('');
    if (value === undefined || value === null) {
      lines.push('*[Not provided]*');
    } else if (Array.isArray(value)) {
      for (const item of value) {
        lines.push(`- ${String(item)}`);
      }
    } else if (typeof value === 'object') {
      lines.push('```json');
      lines.push(JSON.stringify(value, null, 2));
      lines.push('```');
    } else {
      lines.push(String(value));
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by AI-PM Toolkit from template \`${template.id}\`*`);
  lines.push(`*Workflow: ${template.workflow} | Category: ${template.category}*`);
  if (template.approval_required) {
    lines.push(`*Approval required: ${template.approval_gate ?? 'Yes'}*`);
  }
  lines.push('');

  return lines.join('\n');
}

// ── HTML renderer ────────────────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderHtml(template: TemplateEntry, data: Record<string, unknown>): string {
  const sections: string[] = [];

  sections.push(`<!DOCTYPE html>`);
  sections.push(`<html lang="en">`);
  sections.push(`<head>`);
  sections.push(`  <meta charset="UTF-8">`);
  sections.push(`  <meta name="viewport" content="width=device-width, initial-scale=1.0">`);
  sections.push(`  <title>${escapeHtml(template.name)}</title>`);
  sections.push(`  <style>`);
  sections.push(`    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }`);
  sections.push(`    h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }`);
  sections.push(`    .meta { color: #6b7280; font-size: 0.875rem; margin-bottom: 2rem; }`);
  sections.push(`    .field { margin-bottom: 1.5rem; }`);
  sections.push(`    .field h2 { font-size: 1rem; color: #374151; margin-bottom: 0.5rem; }`);
  sections.push(`    .field p, .field li { line-height: 1.6; }`);
  sections.push(`    .not-provided { color: #9ca3af; font-style: italic; }`);
  sections.push(`    pre { background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; }`);
  sections.push(`    code { background: #f3f4f6; padding: 0.125rem 0.375rem; border-radius: 0.25rem; font-size: 0.875em; }`);
  sections.push(`    footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.8125rem; }`);
  sections.push(`    .approval-badge { display: inline-block; background: #fef3c7; color: #92400e; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; margin-top: 0.5rem; }`);
  sections.push(`  </style>`);
  sections.push(`</head>`);
  sections.push(`<body>`);
  sections.push(`  <h1>${escapeHtml(template.name)}</h1>`);
  sections.push(`  <div class="meta">`);
  sections.push(`    ${escapeHtml(template.description)}`);
  sections.push(`  </div>`);

  for (const key of template.required_inputs) {
    const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const value = data[key];

    sections.push(`  <div class="field">`);
    sections.push(`    <h2>${escapeHtml(label)}</h2>`);
    if (value === undefined || value === null) {
      sections.push(`    <p class="not-provided">[Not provided]</p>`);
    } else if (Array.isArray(value)) {
      sections.push(`    <ul>`);
      for (const item of value) {
        sections.push(`      <li>${escapeHtml(String(item))}</li>`);
      }
      sections.push(`    </ul>`);
    } else if (typeof value === 'object') {
      sections.push(`    <pre><code>${escapeHtml(JSON.stringify(value, null, 2))}</code></pre>`);
    } else {
      sections.push(`    <p>${escapeHtml(String(value))}</p>`);
    }
    sections.push(`  </div>`);
  }

  sections.push(`  <footer>`);
  sections.push(`    Generated by AI-PM Toolkit from template <code>${escapeHtml(template.id)}</code>`);
  sections.push(`    <br>Workflow: ${escapeHtml(template.workflow)} | Category: ${escapeHtml(template.category)}`);
  if (template.approval_required) {
    sections.push(`    <br><span class="approval-badge">⚠ Approval Required</span>`);
  }
  sections.push(`  </footer>`);
  sections.push(`</body>`);
  sections.push(`</html>`);

  return sections.join('\n');
}

// ── JSON renderer ────────────────────────────────────────────────────────────

function renderJson(template: TemplateEntry, data: Record<string, unknown>): string {
  const output = {
    $schema: `ai-pm-toolkit/artifacts/${template.id}`,
    meta: {
      templateId: template.id,
      templateName: template.name,
      category: template.category,
      workflow: template.workflow,
      ownerRole: template.owner_role,
      approvalRequired: template.approval_required,
      approvalGate: template.approval_gate ?? null,
      renderedAt: new Date().toISOString(),
      version: '1.0.0',
    },
    content: data,
  };
  return JSON.stringify(output, null, 2);
}

// ── Public API ───────────────────────────────────────────────────────────────

export function renderArtifact(
  template: TemplateEntry,
  data: Record<string, unknown>,
  format: RenderFormat,
): RenderedArtifact {
  const metadata: ArtifactMetadata = {
    templateId: template.id,
    templateName: template.name,
    category: template.category,
    workflow: template.workflow,
    ownerRole: template.owner_role,
    approvalRequired: template.approval_required,
    renderedAt: new Date().toISOString(),
    version: '1.0.0',
    inputKeys: template.required_inputs,
  };

  let content: string;
  switch (format) {
    case 'markdown':
      content = renderMarkdown(template, data);
      break;
    case 'html':
      content = renderHtml(template, data);
      break;
    case 'json':
      content = renderJson(template, data);
      break;
    default:
      throw new Error(`Unknown render format: ${format}`);
  }

  return { templateId: template.id, format, content, metadata };
}
